// adjectives.ts

const adjectives: string[] = [
    "vibrant",
    "serene",
    "mystic",
    "radiant",
    "gentle",
    "swift",
    "bold",
    "quiet",
    "ancient",
    "modern",
    "sparkling",
    "gloomy",
    "happy",
    "sad",
    "wild",
    "tame",
    "bitter",
    "sweet",
    "sharp",
    "soft",
    "tiny",
    "huge",
    "colorful",
    "dull",
    "warm",
    "cold",
    "crisp",
    "smooth",
    "rough",
    "fragrant",
    "silent",
    "noisy",
    "luminous",
    "shadowy",
    "ethereal",
    "earthy",
    "celestial",
    "mechanical",
    "organic",
    "synthetic",
    "flowing",
    "static",
    "fleeting",
    "eternal",
    "majestic",
    "humble",
    "precious",
    "common",
    "rare",
    "unique",
  ];
  
  export default adjectives;